### ISSUE TITLE
Rename: scills -> skills

### ISSUE THREAD

**Issue by mr-mig** [Alexe1900/rsschool-cv#3]
https://github.com/Alexe1900/rsschool-cv/blob/6f719e9f9fc2d5d4474cdd6d75429cf05ccf49da/index.html#L35

👋🏼  I've noticed a small typo in your CV (`scills` instead of `skills`).
You may want to rename it across the code

**Comment by Alexe1900** [comment]
OK!

**Comment by Alexe1900** [comment]
I've fixed this issue! 🙌✊
